
    -   name: "回国SS"
        type: ss
        server: wunifeng.f3322.net
        port: 21520
        cipher: aes-256-cfb
        password: "wu221182"

    -   name: "Vultr悉尼V2Ray"
        type: vmess
        server: www.xqcul.com
        port: 443
        uuid: cee4e788-6c98-19f5-3a9c-e1a14f45858f
        alterId: 32
        cipher: auto
        # udp: true
        tls: true
        # skip-cert-verify: true
        network: ws
        ws-path: /v_2_ray-www
        # ws-headers:
        Host: www.xqcul.com

    -   name: "腾讯云香港V2Ray"
        type: vmess
        server: www.dashui8.com
        port: 443
        uuid: cee4e788-6c98-19f5-3a9c-e1a14f45858f
        alterId: 32
        cipher: auto
        # udp: true
        tls: true
        # skip-cert-verify: true
        network: ws
        ws-path: /ray
        # ws-headers:
        Host: www.dashui8.com

    -   name: "UFO香港Trojan"
        type: trojan
        server: www.zucaipro.ga
        port: 443
        password: mytrojan001
        # udp: true
        # sni: example.com # aka server name
        # alpn:
        #   - h2
        #   - http/1.1
        # skip-cert-verify: true

    -   name: "谷歌云香港Trojan"
        type: trojan
        server: www.zucaipro.tk
        port: 443
        password: mytrojan001

    -   name: "阿里云香港Trojan"
        type: trojan
        server: www.zucaipro.ml
        port: 443
        password: mytrojan001
